services:
  vue-production:
    build:
      context: .
      target: production
      args:
        VITE_API_URL: https://ultralink.cloud/api
        VITE_REVERB_APP_KEY: "fr6ej145c0m9njsh6npy"
        VITE_REVERB_HOST: "ultralink.cloud"
        VITE_REVERB_PORT: 443
        VITE_REVERB_SCHEME: "https"
        VITE_REVERB_PATH: ""
    image: my-front-production:latest
    container_name: my-front-production-container
    ports:
      - 3000:80
